version: "3"
services:
  pg:
    image: postgres:14
    ports:
      - "55432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb

